package com.qin.video.model;


import com.qin.video.model.base.BaseTheme;
import com.ruoyi.common.jfinal.annotation.Table;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Table(tableName = "User", primaryKey = "id", clazz = Theme.class)
public class Theme extends BaseTheme<Theme> {
	
}
